name: offline_liturgy
description: A liturgy package.
version: 2.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

flutter:
  assets:
    - assets/locations.json
    - assets/calendar_data/commons/
    - assets/calendar_data/ferial_days/
    - assets/calendar_data/special_days/
    - assets/calendar_data/sanctoral/
    - assets/common_data/psalms_library.json
    - assets/common_data/psalms_library_greek_hebrew.json
    - assets/common_data/hymns_library.json

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
